# Pack VPM zip for local VCC listing
# Usage: powershell -File scripts/pack-vpm.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$pkg = Join-Path $root "Packages\dev.ova.protection"
$pj = Join-Path $pkg "package.json"
if (-not (Test-Path $pj)) { throw "missing $pj" }

$meta = Get-Content -Raw -Encoding UTF8 $pj | ConvertFrom-Json
$ver = [string]$meta.version
$outDir = Join-Path $root "Releases"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$zipName = "dev.ova.protection-$ver.zip"
$zip = Join-Path $outDir $zipName
if (Test-Path $zip) { Remove-Item -Force $zip }

$stage = Join-Path $env:TEMP ("ova-vpm-" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Force -Path $stage | Out-Null
try {
    Copy-Item -Recurse -Force -Path (Join-Path $pkg "*") -Destination $stage
    Compress-Archive -Path (Join-Path $stage "*") -DestinationPath $zip -CompressionLevel Optimal
} finally {
    Remove-Item -Recurse -Force $stage
}

$hash = (Get-FileHash -Algorithm SHA256 $zip).Hash.ToLowerInvariant()
$listing = Join-Path $root "source.json"
$zipUrl = ("file:///" + $zip.Replace('\', '/'))
$listingUrl = ("file:///" + $listing.Replace('\', '/'))
$ndmf = ">=1.14.0"
if ($meta.vpmDependencies -and $meta.vpmDependencies.'nadena.dev.ndmf') {
    $ndmf = [string]$meta.vpmDependencies.'nadena.dev.ndmf'
}
$display = [string]$meta.displayName
$desc = [string]$meta.description
$unity = [string]$meta.unity
$vrcVer = [string]$meta.vrchatVersion
$license = [string]$meta.license
# Keep listing version/url in sync with package.json (not a frozen 0.1.0 stub).
$listingJson = @"
{
  "name": "OVA (local)",
  "id": "dev.ova.vpm",
  "url": "$listingUrl",
  "author": {
    "name": "OVA"
  },
  "description": "Local VPM listing for OVA Avatar Protection. Regenerated by scripts/pack-vpm.ps1.",
  "packages": [
    {
      "name": "dev.ova.protection",
      "releases": [
        {
          "name": "dev.ova.protection",
          "displayName": "$display",
          "version": "$ver",
          "unity": "$unity",
          "description": "$desc",
          "vrchatVersion": "$vrcVer",
          "author": {
            "name": "OVA"
          },
          "license": "$license",
          "keywords": ["vrchat", "ndmf", "anti-rip", "obfuscation"],
          "vpmDependencies": {
            "nadena.dev.ndmf": "$ndmf",
            "com.vrchat.avatars": ">=3.5.0"
          },
          "url": "$zipUrl",
          "zipSHA256": "$hash"
        }
      ]
    }
  ]
}
"@
$utf8 = New-Object System.Text.UTF8Encoding $false
[IO.File]::WriteAllText($listing, $listingJson.Trim() + [Environment]::NewLine, $utf8)

Write-Output "zip=$zip"
Write-Output "sha256=$hash"
Write-Output "listing=$listing"
